// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(EvenPaceContext))]
    [Migration("20260126014306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique();

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("Core.AvaliacaoEvento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("comentario");

                    b.Property<int>("Estrela")
                        .HasColumnType("int")
                        .HasColumnName("estrela");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("AvaliacaoEvento", (string)null);
                });

            modelBuilder.Entity("Core.CartaoCredito", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<int>("CodeSeguranca")
                        .HasColumnType("int")
                        .HasColumnName("codeSeguranca");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("date")
                        .HasColumnName("dataValidade");

                    b.Property<uint>("IdCorredor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idCorredor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("char(16)")
                        .HasColumnName("numero")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCorredor" }, "fk_CartaoCredito_Corredor1_idx");

                    b.HasIndex(new[] { "IdCorredor" }, "idCorredor_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Numero" }, "numero_UNIQUE")
                        .IsUnique();

                    b.ToTable("CartaoCredito", (string)null);
                });

            modelBuilder.Entity("Core.Corredor", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("dataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "cpf_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("email_UNIQUE1");

                    b.ToTable("Corredor", (string)null);
                });

            modelBuilder.Entity("Core.Cupom", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("dataInicio");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("date")
                        .HasColumnName("dataTermino");

                    b.Property<int>("Desconto")
                        .HasColumnType("int")
                        .HasColumnName("desconto");

                    b.Property<uint>("IdEvento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEvento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantiadeDisponibilizada")
                        .HasColumnType("int")
                        .HasColumnName("quantiadeDisponibilizada");

                    b.Property<int>("QuantidadeUtilizada")
                        .HasColumnType("int")
                        .HasColumnName("quantidadeUtilizada");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEvento" }, "fk_Cupom_Evento1_idx");

                    b.ToTable("Cupom", (string)null);
                });

            modelBuilder.Entity("Core.Evento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Distancia10")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia10");

                    b.Property<bool>("Distancia15")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia15");

                    b.Property<bool>("Distancia21")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia21");

                    b.Property<bool>("Distancia3")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia3");

                    b.Property<bool>("Distancia42")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia42");

                    b.Property<bool>("Distancia5")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia5");

                    b.Property<bool>("Distancia7")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("distancia7");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("estado");

                    b.Property<uint>("IdOrganizacao")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idOrganizacao");

                    b.Property<string>("InfoRetiradaKit")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("infoRetiradaKit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<int>("NumeroParticipantes")
                        .HasColumnType("int")
                        .HasColumnName("numeroParticipantes");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("rua");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdOrganizacao" }, "fk_Evento_Organizacao_idx");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("Core.Inscricao", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("date")
                        .HasColumnName("dataInscricao");

                    b.Property<string>("Distancia")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("distancia");

                    b.Property<uint>("IdAvaliacaoEvento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idAvaliacaoEvento");

                    b.Property<uint>("IdCorredor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idCorredor");

                    b.Property<uint>("IdEvento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEvento");

                    b.Property<uint>("IdKit")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idKit");

                    b.Property<int>("Posicao")
                        .HasColumnType("int")
                        .HasColumnName("posicao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("status");

                    b.Property<string>("TamanhoCamisa")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("tamanhoCamisa");

                    b.Property<TimeSpan>("Tempo")
                        .HasColumnType("time")
                        .HasColumnName("tempo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAvaliacaoEvento" }, "fk_Inscricao_AvaliacaoEvento1_idx");

                    b.HasIndex(new[] { "IdCorredor" }, "fk_Inscricao_Corredor1_idx");

                    b.HasIndex(new[] { "IdEvento" }, "fk_Inscricao_Evento1_idx");

                    b.HasIndex(new[] { "IdKit" }, "fk_Inscricao_Kit1_idx");

                    b.ToTable("Inscricao", (string)null);
                });

            modelBuilder.Entity("Core.Kit", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime")
                        .HasColumnName("dataRetirada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descricao");

                    b.Property<int>("DisponibilidadeG")
                        .HasColumnType("int")
                        .HasColumnName("disponibilidadeG");

                    b.Property<int>("DisponibilidadeM")
                        .HasColumnType("int")
                        .HasColumnName("disponibilidadeM");

                    b.Property<int>("DisponibilidadeP")
                        .HasColumnType("int")
                        .HasColumnName("disponibilidadeP");

                    b.Property<uint>("IdEvento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEvento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.Property<bool>("StatusRetiradaKit")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("statusRetiradaKit");

                    b.Property<sbyte>("UtilizadaG")
                        .HasColumnType("tinyint")
                        .HasColumnName("utilizadaG");

                    b.Property<sbyte>("UtilizadaM")
                        .HasColumnType("tinyint")
                        .HasColumnName("utilizadaM");

                    b.Property<sbyte>("UtilizadaP")
                        .HasColumnType("tinyint")
                        .HasColumnName("utilizadaP");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEvento" }, "fk_Kit_Evento1_idx");

                    b.ToTable("Kit", (string)null);
                });

            modelBuilder.Entity("Core.Organizacao", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int")
                        .HasColumnName("Administrador_id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("estado");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha");

                    b.Property<bool>("StatusSituacao")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("statusSituacao");

                    b.Property<int>("Telefone")
                        .HasColumnType("int")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cnpj" }, "cnpj_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("email_UNIQUE2");

                    b.HasIndex(new[] { "AdministradorId" }, "fk_Organizacao_Admistrador1_idx");

                    b.ToTable("Organizacao", (string)null);
                });

            modelBuilder.Entity("Core.CartaoCredito", b =>
                {
                    b.HasOne("Core.Corredor", "IdCorredorNavigation")
                        .WithOne("CartaoCredito")
                        .HasForeignKey("Core.CartaoCredito", "IdCorredor")
                        .IsRequired()
                        .HasConstraintName("fk_CartaoCredito_Corredor1");

                    b.Navigation("IdCorredorNavigation");
                });

            modelBuilder.Entity("Core.Cupom", b =>
                {
                    b.HasOne("Core.Evento", "IdEventoNavigation")
                        .WithMany("Cupoms")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("fk_Cupom_Evento1");

                    b.Navigation("IdEventoNavigation");
                });

            modelBuilder.Entity("Core.Evento", b =>
                {
                    b.HasOne("Core.Organizacao", "IdOrganizacaoNavigation")
                        .WithMany("Eventos")
                        .HasForeignKey("IdOrganizacao")
                        .IsRequired()
                        .HasConstraintName("fk_Evento_Organizacao");

                    b.Navigation("IdOrganizacaoNavigation");
                });

            modelBuilder.Entity("Core.Inscricao", b =>
                {
                    b.HasOne("Core.AvaliacaoEvento", "IdAvaliacaoEventoNavigation")
                        .WithMany("Inscricaos")
                        .HasForeignKey("IdAvaliacaoEvento")
                        .IsRequired()
                        .HasConstraintName("fk_Inscricao_AvaliacaoEvento1");

                    b.HasOne("Core.Corredor", "IdCorredorNavigation")
                        .WithMany("Inscricaos")
                        .HasForeignKey("IdCorredor")
                        .IsRequired()
                        .HasConstraintName("fk_Inscricao_Corredor1");

                    b.HasOne("Core.Evento", "IdEventoNavigation")
                        .WithMany("Inscricaos")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("fk_Inscricao_Evento1");

                    b.HasOne("Core.Kit", "IdKitNavigation")
                        .WithMany("Inscricaos")
                        .HasForeignKey("IdKit")
                        .IsRequired()
                        .HasConstraintName("fk_Inscricao_Kit1");

                    b.Navigation("IdAvaliacaoEventoNavigation");

                    b.Navigation("IdCorredorNavigation");

                    b.Navigation("IdEventoNavigation");

                    b.Navigation("IdKitNavigation");
                });

            modelBuilder.Entity("Core.Kit", b =>
                {
                    b.HasOne("Core.Evento", "IdEventoNavigation")
                        .WithMany("Kits")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("fk_Kit_Evento1");

                    b.Navigation("IdEventoNavigation");
                });

            modelBuilder.Entity("Core.Organizacao", b =>
                {
                    b.HasOne("Core.Administrador", "Administrador")
                        .WithMany("Organizacaos")
                        .HasForeignKey("AdministradorId")
                        .HasConstraintName("fk_Organizacao_Admistrador1");

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("Core.Administrador", b =>
                {
                    b.Navigation("Organizacaos");
                });

            modelBuilder.Entity("Core.AvaliacaoEvento", b =>
                {
                    b.Navigation("Inscricaos");
                });

            modelBuilder.Entity("Core.Corredor", b =>
                {
                    b.Navigation("CartaoCredito");

                    b.Navigation("Inscricaos");
                });

            modelBuilder.Entity("Core.Evento", b =>
                {
                    b.Navigation("Cupoms");

                    b.Navigation("Inscricaos");

                    b.Navigation("Kits");
                });

            modelBuilder.Entity("Core.Kit", b =>
                {
                    b.Navigation("Inscricaos");
                });

            modelBuilder.Entity("Core.Organizacao", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
