// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class OTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("https://localhost:7131/"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void o() {
    driver.Navigate().GoToUrl("https://localhost:7131/");
    driver.Manage().Window.Size = new System.Drawing.Size(790, 816);
    driver.FindElement(By.LinkText("Entrar como Organização")).Click();
    driver.FindElement(By.Id("Input_Email")).SendKeys("teste@gmail.com");
    driver.FindElement(By.Id("Input_Password")).SendKeys("123456");
    driver.FindElement(By.LinkText("Cadastre-se aqui")).Click();
    driver.FindElement(By.Id("Input_Cpf")).Click();
    driver.FindElement(By.Id("Input_Cpf")).SendKeys("12345678923");
    driver.FindElement(By.Id("Input_Email")).SendKeys("teste@gmail.com");
    driver.FindElement(By.Id("registerForm")).Click();
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("123456");
    driver.FindElement(By.Id("Input_ConfirmPassword")).Click();
    driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("123456");
    driver.FindElement(By.Id("registerSubmit")).Click();
    driver.FindElement(By.CssSelector("ul")).Click();
    Assert.That(driver.FindElement(By.CssSelector("li")).Text, Is.EqualTo("CPF já cadastrado."));
  }
}
