// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EditarCupomVlidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
    }
  [Test]
  public void editarCupomVlido() {
    driver.Navigate().GoToUrl("http://127.0.0.1:5157/Cupom/Index");
    driver.Manage().Window.Size = new System.Drawing.Size(1742, 856);
    driver.FindElement(By.LinkText("Editar")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("PROMO30");
    driver.FindElement(By.Id("Desconto")).Click();
    driver.FindElement(By.Id("Desconto")).SendKeys("30");
    driver.FindElement(By.CssSelector(".btn-save")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td > .fw-bold")).Text, Is.EqualTo("PROMO30"));
  }
}
