// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EditardatadecupominvalidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void editardatadecupominvalida() {
    driver.Navigate().GoToUrl("https://localhost:7131/Cupom/Index");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector("tr:nth-child(2) .btn-outline-dark")).Click();
    driver.FindElement(By.Id("DataTermino")).Click();
    driver.FindElement(By.Id("DataTermino")).SendKeys("2026-05-20");
    driver.FindElement(By.CssSelector(".btn-save")).Click();
  }
}
