// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InscreverseemduascorridasdiferentesTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
    }
  [Test]
  public void inscreverseemduascorridasdiferentes() {
    driver.Navigate().GoToUrl("http://localhost:5157/Evento/IndexUsuario");
    driver.Manage().Window.Size = new System.Drawing.Size(1742, 856);
    driver.FindElement(By.CssSelector("a:nth-child(1) .btn-inscrever")).Click();
    driver.FindElement(By.CssSelector(".btn-inscrever")).Click();
    driver.FindElement(By.CssSelector(".opcoes:nth-child(8) > .opcao-label:nth-child(3) > .checkmark")).Click();
    driver.FindElement(By.CssSelector(".opcoes:nth-child(10) > .opcao-label:nth-child(2) > .checkmark")).Click();
    driver.FindElement(By.CssSelector(".btn-confirmar")).Click();
    driver.FindElement(By.CssSelector("a:nth-child(2) .btn-inscrever")).Click();
    driver.FindElement(By.CssSelector(".btn-inscrever")).Click();
    driver.FindElement(By.CssSelector(".opcoes:nth-child(8) > .opcao-label:nth-child(3) > .checkmark")).Click();
    driver.FindElement(By.CssSelector(".opcoes:nth-child(10) > .opcao-label:nth-child(2) > .checkmark")).Click();
    driver.FindElement(By.CssSelector(".btn-confirmar")).Click();
    var elements = driver.FindElements(By.CssSelector("a:nth-child(1) img"));
    Assert.That(elements.Count > 0);
  }
}
