// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserirCupomComDescontoInvalidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
  }
  [Test]
  public void inserirCupomComDescontoInvalido() {
    driver.Navigate().GoToUrl("http://127.0.0.1:5157/Cupom/Create");
    driver.Manage().Window.Size = new System.Drawing.Size(1280, 1410);
    {
      var dropdown = driver.FindElement(By.Id("IdEvento"));
      dropdown.FindElement(By.XPath("//option[. = 'Corrida Ibirapuera']")).Click();
    }
    driver.FindElement(By.CssSelector("option:nth-child(3)")).Click();
    driver.FindElement(By.Id("DataInicio")).Click();
    driver.FindElement(By.Id("DataInicio")).Click();
    driver.FindElement(By.Id("DataInicio")).Click();
    driver.FindElement(By.Id("DataInicio")).SendKeys("2026-05-22");
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    {
      var element = driver.FindElement(By.Id("Nome"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("Nome")).SendKeys("VERAO10");
    driver.FindElement(By.Id("DataTermino")).Click();
    driver.FindElement(By.Id("DataTermino")).SendKeys("2026-06-12");
    driver.FindElement(By.Id("Desconto")).Click();
    driver.FindElement(By.Id("Desconto")).SendKeys("100");
    driver.FindElement(By.Id("QuantiadeDisponibilizada")).Click();
    driver.FindElement(By.Id("QuantiadeDisponibilizada")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-save")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".field-validation-error")).Text, Is.EqualTo("O desconto deve ser maior que zero e menor que 100."));
  }
}
