// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserircupomvalidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void inserircupomvalido() {
    driver.Navigate().GoToUrl("https://localhost:7131/Cupom/Index");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.LinkText("Criar Cupom")).Click();
    driver.FindElement(By.Id("IdEvento")).Click();
    {
      var dropdown = driver.FindElement(By.Id("IdEvento"));
      dropdown.FindElement(By.XPath("//option[. = 'Corrida Beira Mar']")).Click();
    }
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("INVERNO15");
    driver.FindElement(By.Id("DataInicio")).Click();
    driver.FindElement(By.Id("DataInicio")).SendKeys("2026-05-22");
    driver.FindElement(By.Id("DataTermino")).Click();
    driver.FindElement(By.Id("DataTermino")).SendKeys("2026-05-24");
    driver.FindElement(By.Id("Desconto")).Click();
    driver.FindElement(By.Id("Desconto")).SendKeys("15");
    driver.FindElement(By.Id("QuantiadeDisponibilizada")).Click();
    driver.FindElement(By.Id("QuantiadeDisponibilizada")).SendKeys("40");
    driver.FindElement(By.CssSelector(".btn-save")).Click();
  }
}
