// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserirCupomComDataInvalidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
  }
  [Test]
  public void inserirCupomComDataInvalida() {
    driver.Navigate().GoToUrl("http://127.0.0.1:5157/Cupom/Create");
    driver.Manage().Window.Size = new System.Drawing.Size(1280, 1410);
    {
      var dropdown = driver.FindElement(By.Id("IdEvento"));
      dropdown.FindElement(By.XPath("//option[. = 'Corrida Beira Mar']")).Click();
    }
    driver.FindElement(By.CssSelector("option:nth-child(2)")).Click();
    driver.FindElement(By.Id("DataInicio")).Click();
    driver.FindElement(By.Id("DataInicio")).Click();
    driver.FindElement(By.Id("DataInicio")).SendKeys("2026-05-20");
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("VERAO10");
    driver.FindElement(By.Id("DataTermino")).Click();
    driver.FindElement(By.Id("DataTermino")).SendKeys("2026-05-13");
    driver.FindElement(By.Id("Desconto")).Click();
    driver.FindElement(By.Id("Desconto")).SendKeys("10");
    driver.FindElement(By.Id("QuantiadeDisponibilizada")).Click();
    driver.FindElement(By.Id("QuantiadeDisponibilizada")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-save")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .mb-3:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".mb-3:nth-child(2) > .text-danger:nth-child(4)")).Text, Is.EqualTo("A data de término deve ser maior que a data de início."));
  }
}
