// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class InscricaoDuplicadaTest
{
    private IWebDriver driver;
    private WebDriverWait wait;

    [SetUp]
    public void IniciarTeste()
    {
        driver = new ChromeDriver();
        driver.Manage().Window.Maximize();

        wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
    }

    [TearDown]
    public void EncerrarTeste()
    {
        driver.Quit();
    }

    [Test]
    public void ValidarTentativaDeInscricaoDuplicada()
    {
        driver.Navigate().GoToUrl("https://localhost:7131/");
      driver.Manage().Window.Size = new System.Drawing.Size(790, 816);
        driver.FindElement(By.LinkText("Entrar como Corredor")).Click();
        driver.FindElement(By.Id("email")).SendKeys("teste@gmail.com");
        driver.FindElement(By.Id("senha")).SendKeys("123456");
        driver.FindElement(By.CssSelector(".evenpace-btn-yellow")).Click();
        wait.Until(d => d.FindElement(By.CssSelector(".btn-inscrever")));
        driver.FindElement(By.CssSelector(".btn-inscrever")).Click();
        wait.Until(d => d.FindElement(By.CssSelector(".kit-card")));
        driver.FindElement(By.CssSelector(".kit-card .btn-inscrever")).Click();

        wait.Until(d => d.FindElement(By.XPath("//label[contains(text(),'5Km')]")));
        driver.FindElement(By.XPath("//label[contains(text(),'5Km')]")).Click();
        driver.FindElement(By.XPath("//label[contains(text(),'M')]")).Click();
        driver.FindElement(By.CssSelector(".btn-confirmar")).Click();

        IWebElement mensagemErro = wait.Until(
            d => d.FindElement(By.ClassName("swal2-popup"))
        );

        Assert.IsTrue(
            mensagemErro.Text.Contains("já possui uma inscrição") ||
            mensagemErro.Text.Contains("inscrição para este evento")
        );
    }
}
