// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class UntitledTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("https://localhost:7131/"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void untitled() {
    driver.Navigate().GoToUrl("https://localhost:7131/");
    driver.Manage().Window.Size = new System.Drawing.Size(790, 816);
    driver.FindElement(By.LinkText("Entrar como Corredor")).Click();
    driver.FindElement(By.Id("email")).SendKeys("teste@gmail.com");
    driver.FindElement(By.Id("senha")).SendKeys("123456");
    driver.FindElement(By.Id("cpf")).Click();
    driver.FindElement(By.Id("cpf")).SendKeys("12345678912");
    driver.FindElement(By.CssSelector(".evenpace-btn-yellow")).Click();
    driver.FindElement(By.CssSelector("a:nth-child(1) .btn-inscrever")).Click();
    driver.FindElement(By.CssSelector(".kit-card:nth-child(10) > .btn-inscrever")).Click();
    driver.FindElement(By.CssSelector(".opcoes:nth-child(8) > .opcao-label:nth-child(2) > .checkmark")).Click();
    driver.FindElement(By.CssSelector(".opcoes:nth-child(10) > .opcao-label:nth-child(1) > .checkmark")).Click();
    driver.FindElement(By.CssSelector(".btn-confirmar")).Click();
  }
}
